"""create column completed_at in Projects

Revision ID: 1615466565dd
Revises: b3dbf64037d4
Create Date: 2026-05-13 10:18:18.292302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1615466565dd'
down_revision: Union[str, Sequence[str], None] = 'b3dbf64037d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'completed_at')
    # ### end Alembic commands ###
