"""added two column to users

Revision ID: a359cfadac20
Revises: 79634d6dc5df
Create Date: 2026-05-05 20:56:34.187919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a359cfadac20"
down_revision: Union[str, Sequence[str], None] = "79634d6dc5df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("reset_code", sa.String(length=8), nullable=True))
    op.add_column(
        "users",
        sa.Column("reset_code_expire", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reset_code_expire")
    op.drop_column("users", "reset_code")
    # ### end Alembic commands ###
