"""add project category

Revision ID: 870847461cf5
Revises: 8ccc3f1b1c2f
Create Date: 2026-04-30 17:58:32.477203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870847461cf5'
down_revision: Union[str, Sequence[str], None] = '8ccc3f1b1c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('projects', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'project_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'category_id')
    op.drop_table('project_categories')
    # ### end Alembic commands ###
