"""remove is_draft from projects

Revision ID: 183cb0ad8c16
Revises: aaca26fc121c
Create Date: 2026-05-06 11:12:47.159754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183cb0ad8c16'
down_revision: Union[str, Sequence[str], None] = 'aaca26fc121c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_vacancies', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('projects', 'is_draft')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_draft', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('project_vacancies', 'id')
    # ### end Alembic commands ###
