"""update projects table

Revision ID: 247e7087111b
Revises: 632eb93cd0a7
Create Date: 2026-05-06 16:46:49.409155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247e7087111b'
down_revision: Union[str, Sequence[str], None] = '632eb93cd0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'id')
    op.drop_column('project_technologies', 'id')
    op.drop_column('project_vacancies', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_vacancies', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project_technologies', sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.add_column('project_members', sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
