"""remove courser_year from users table

Revision ID: 81e10a8f2138
Revises: 7511e9a5d519
Create Date: 2026-05-13 10:51:53.473750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e10a8f2138'
down_revision: Union[str, Sequence[str], None] = '7511e9a5d519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course_year', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
